---

- hosts: all
  become: true
  pre_tasks:

  - name: install update Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update Fedora
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu
    tags: ubuntu,apache,apache2
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php for Ferora
    tags: fedora,apache,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Copy default html file
    tags: apache2,apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: 0644

- hosts: file_servers
  become: true
  tasks:

  - name: install file server for Ubuntu and Fedora
    tags: samba
    package:
      name: samba
      state: latest

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb for Fedora
    tags: fedora,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"

  - name: install mariadb for Ubuntu
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

