---

- hosts: all
  become: true
  tasks:

  - name: install update cache,apache and php package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
