---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "24.04"

  - name: install apache2 and php package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "24.04"

  - name: update repository index Fedora
    yum:
      update_cache: yes
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "41"

  - name: install HTTPD and php package Fedora
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "41"
