---

- hosts: all
  become: true
  tasks:

  - name: install update cache, apache and php package for Ubuntu
    apt:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes

  - name: install update cache, httpd and php package for Fedora
    yum:
      - httpd
      - php
    state: latest
    update_cache: yes
